# Generated by Django 5.2.4 on 2025-07-10 23:27

import django.db.models.deletion
import review_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=review_app.models.increment_food_code, editable=False, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_food', to='review_app.category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='review_app.foodplace')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_food', to='review_app.statusmodel')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_food', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_food', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
