# Generated by Django 5.2.4 on 2025-07-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0006_foodreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Tidak Ada', 'Tidak Ada')], default='Aktif', max_length=15),
        ),
    ]
