# Generated by Django 5.2.4 on 2025-07-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0007_alter_statusmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreview',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_app.foodplace'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15),
        ),
    ]
